# Theme properties for InstaGenius Keycloak theme
parent=keycloak
import=common/keycloak

# Styles
styles=css/styles.css

# Scripts
scripts=js/script.js

# Meta
meta=viewport==width=device-width,initial-scale=1

# Custom properties
kcHtmlClass=instagenius-theme
kcLoginClass=brand-container
kcFormCardClass=form-container
kcButtonClass=button
kcButtonPrimaryClass=primary
kcInputClass=form__control--input
kcLabelClass=form__control--label