package com.instagenius.postgenerationservice.domain;

public record PostGenerationOptions(DescriptionGenerationOptions descriptionGenerationOptions, ImageGenerationOptions imageGenerationOptions) {
}
