spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coin_management
    driver-class-name: org.postgresql.Driver
    username: ${COIN_MANAGEMENT_DB_USERNAME}
    password: ${COIN_MANAGEMENT_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 8040