spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  datasource:
    url: ${COIN_MANAGEMENT_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${COIN_MANAGEMENT_DB_USERNAME}
    password: ${COIN_MANAGEMENT_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: ${COIN_MANAGEMENT_PORT}