spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8180/auth/realms/instagenius}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: post-management-service
          uri: lb://POST-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/posts/**
        - id: coin-management-service
          uri: lb://COIN-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/coins/**
server:
  port: ${GATEWAY_SERVICE_PORT:8000}
