spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${GATEWAY_DISCOVERY_LOCATOR_ENABLED}
      routes:
        - id: post-management-service
          uri: lb://${POST_MANAGEMENT_SERVICE_URI}
          predicates:
            - Path=${GATEWAY_POST_MANAGEMENT_SERVICE_PATH}
        - id: coin-management-service
          uri: lb://${GATEWAY_COIN_MANAGEMENT_SERVICE_URI}
          predicates:
            - Path=${GATEWAY_COIN_MANAGEMENT_SERVICE_PATH}
server:
  port: ${GATEWAY_PORT}
