spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8180/auth/realms/instagenius}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POST_MANAGEMENT_DB_HOST:localhost}:${POST_MANAGEMENT_DB_PORT:5432}/${POST_MANAGEMENT_DB_NAME:db_posts}
    username: ${POST_MANAGEMENT_DB_USERNAME:post_management_service_user}
    password: ${POST_MANAGEMENT_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${POST_MANAGEMENT_SERVICE_PORT:8083}
application:
  config:
    post-generation-url: ${FEIGN_CLIENT_GENERATION_URL:http://localhost:8082/api/v1/generate}
aws:
  access-key: ${AWS_ACCESS_KEY:some-access-key}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:some-secret-access-key}
  region: ${AWS_REGION:some-region}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:some-bucket-name}