spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        enabled: true
      image:
        enabled: true
server:
  port: 8000