spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post_management
    username: ${POST_MANAGEMENT_DB_USERNAME}
    password: ${POST_MANAGEMENT_DB_PASSWORD}
  jpa:
    hibernate: #TODO sprawdzic czy to jest prawdidlwoe na intellij ultimate
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway: #TODO sprawdzic do czego dokladnie sluzy flyway
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8020
