spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/post_management
    username: post_management_service_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8020
application:
  config:
    post-generation-url: http://localhost:8000/api/v1/post-generation #TODO change after  to post of cloud gateway
