spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POST_MANAGEMENT_DB_URL}
    username: ${POST_MANAGEMENT_DB_USERNAME}
    password: ${POST_MANAGEMENT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${POST_MANAGEMENT_SERVICE_PORT}
application:
  config:
    post-generation-url: ${FEIGN_CLIENT_GENERATION_URL}
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}