server:
  port: ${CONFIG_SERVICE_PORT}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SERVICE_NATIVE_SEARCH_LOCATIONS}